function figure_force_pCa_norm
% Function creates a figure showing force_pCa normilezed fits

% Path
addpath(genpath('../../MATLAB_Utilities'))

% Variables 
sim_data_folder = '../Simulations/specific_molecules/sim_data/sim_output';
data_file_string =  ';
output_image_file = '../output/pCa_curves';
output_image_types = {'png', 'svg', 'eps'};
% conditions_to_draw =  [1, 2, 5, 6]

% Display 
color_map = [1 0 0.2 ; 0.5 0.6 1 ; 0 0 1 ; 0.4 0.7 0.9 ; ...
             1 0.7 0.3 ; 0.8 0 1; 0 0.8 0.8];

% Code 

% Figure 
no_of_cols = 1
no_of_rows = 1 

sp = initialise_publication_quality_figure(...
    'no_of_panels_wide', no_of_cols,...
    'no_of_panels_high', no_of_rows, ...
    'x_to_y_axes_ratio', 0.9, ...
    'right_margin', 1, ...
    'axes_padding_top', 0 , ...
    'axes_padding_bottom', 0.4, ...
    'panel_label_font_size', 0, ...
    'individual_padding', 7,...
    'left_pads', repmat([0.7, 0.2, 0.4], [1, 6]), ...
    'right_pads', repmat([0.6, 0.2, 0.2], [1, 6]),...
    'top_margin', 0.4, ...
    'bottom_margin', 0.2)


% Read files 
t = readtable(data_file_string)
